project_name: clsmt
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
- image_templates: ["clsmt:{{ .Version }}"]
  dockerfile: Dockerfile
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/lovelacelee/mirror-tools
  - --label=org.opencontainers.image.source=https://github.com/lovelacelee/mirror-tools
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
nfpms:
- maintainer: Lovelace <lovelacelee@gmail.com>
  description: clsmt personal assistant.
  homepage: https://github.com/lovelacelee/mirror-tools
  license: MIT
  formats:
  - deb
  - rpm
  - exe